import createError from "../utils/createError.js"


export const createMessage = async (req,res,next) =>{

    try {
        
    } catch (error) {
        next(error)
    }
}